calblueprint/ogsc

package.json
prisma/schema.prisma
yarn.lock

* Add two dependencies, @prisma/client and @prisma/cli 
* Update Prisma schema to match the initial introspection (in this case, from the `migrations` table automatically created/managed by db-migrate)
* Create a `prisma/.env` file with only these contents (update to match your local DB setup details):
```
DATABASE_URL=postgresql://<your macOS username>:@localhost:<the Postgres port, probably 5432>/ogsc_development
```
* Run `yarn` to install new dependencies
* Run `yarn prisma generate`
CC: @erinysong

Add @prisma/client, @prisma/cli with initial introspection

---

bin/create-migration.ts
migrations/20201004045528-AddNextAuthUsersTable.ts
migrations/20201004045528-AddNextAuthUsersTable .js
package.json
prisma/schema.prisma
yarn.lock

* Adds next-auth dependency
* Adds initial migration from NextAuth for users table (groundwork for authentication effort with @joyydong) — we are splitting out this PR early so that others can work off of a users table
* Uses TypeScript for migrations, using a forked version of [db-migrate-plugin-typescript](https://github.com/ethanlee16/plugin-typescript)
* Adds `bin/create-migration.ts` as a replacement for creating template migrations that are ESLint + TS-compliant
* Must run `yarn` as new deps were added.
* All `db-migrate` commands moving forward should be issued with `yarn db:migrate` instead of `yarn db-migrate`. This will load the migrations environment with `ts-node`.
* Migrations should now be created with `yarn db:migrate:create <NameOfMigration>` instead of `yarn db-migrate …

Users table initial migration + TS support for migrations

---

.eslintrc.js
migrations/20201006040029-AddPasswordToUsers.ts
package.json
pages/api/auth/[...nextauth].ts
prisma/schema.prisma
yarn.lock

- Wrote starting code for the NextAuth account authorization endpoint (with much support and guidance from @ethanlee16)
- Added migration for storing password
- Updated ts eslint no-unused-vars rule 
@shannonmhong @christopher-grey take a look at [line 11 in [...nextauth].ts](https://github.com/calblueprint/ogsc/commit/7961dbaa16222dbfffe6173c51675016fd164f93#diff-3f0eb5f8ea11c33e06c794b69418f4eeL11), was thinking user metadata (i.e. viewing permissions) could be stored in the `AuthorizeDTO` user type?
- Run yarn (added NextAuth types)
- Add the database url to the root `.env` file (the line that is already in your `prisma/.env` file)
`DATABASE_URL=postgresql://joydong:@localhost:5432/ogsc_development`
- **AddPasswordToUsers**: Adds a `hashed_password` field to the `users` table
CC: …

Basic authorization endpoint + .env changes

---

.vscode/settings.json
migrations/20201009072158-UniquePlayerUserIdConstraint.ts
migrations/20201009074558-AddUUIDExtension.ts
migrations/20201009074559-CreateUserInvitesTable.ts
pages/api/auth/[...nextauth].ts
prisma/schema.prisma

* Updates some Prisma model names to PascalCase singular form, with the use of `@map` and `@@map` annotations
* Creates `user_invites` table
* `20201009074558-AddUUIDExtension`: The primary key of `user_invites` is a string type, auto-generated UUID. This migration adds the UUID extension to the PostgreSQL database, if it doesn't already have it.
* `20201009074559-CreateUserInvitesTable`: Creates the `user_invites` table.
CC: @erinysong

Add user invites table + fix some Prisma model names

---

interfaces/index.ts
package.json
pages/api/auth/[...nextauth].ts
pages/api/invites/[id].ts
utils/sanitizeUser.ts
yarn.lock

* Adds an API route/reusable function for getting an invite by its ID (this ID would be included in the invite link URL)
* Breaks out `stripPassword` function into generic utility for `sanitizeUser`, with `SanitizedUser` type
CC: @erinysong

Add getInviteById API route + break out sanitizeUser shared function

---

components/List.tsx
components/ListDetail.tsx
components/ListItem.tsx
package.json
pages/api/hello.ts
pages/api/invites/[id].ts
pages/users/[id].tsx
pages/users/index.tsx
prisma/schema.prisma
utils/sample-data.ts
yarn.lock

This addresses a couple current issues present in the main branch:
* Duplicate `User` and `users` models in Prisma schema. This might have been the result of a merge commit. **If you were previously using `prisma.users`, please update references to `prisma.user`!**
* Type errors in some of the placeholder pages/components as a result of deleting the placeholder `User` interface. I moved this interface to `utils/sample-data` for now (until these placeholders are deleted) to avoid confusion with our actual User/SanitizedUser interfaces.
This PR also switches out the `validator` package for [`joi`](https://joi.dev/api/?v=17.2.1), which will be produce more readable code for validating nested objects like `req.body` in our Next API routes. I've demonstrated the use of Joi at the end of a …

Schema hotfix, move to Joi for validation, resolve type errors

---

pages/api/auth/[...nextauth].ts
pages/api/invites/[id].ts
pages/api/invites/index.ts
pages/api/users/index.ts
prisma/schema.prisma
utils/hashPassword.ts

- Account creation (i.e. user signup, with or without invite code)
- Wrote user endpoint and updated authorize call to just check password
(rest of the changes are Ethan's! I was working on his branch)
- Breaks out hashPassword function for generic utility 
- Start of invite creation endpoint
- Bug fix: `getInviteById` should check for error and return null if it exists
CC: @erinysong

Finished account creation flow / endpoint

---

components/schema.sql
package-lock.json
pages/api/users/create.ts
pages/api/users/createUser.ts
pages/api/users/delete.ts
pages/api/users/read.ts
pages/api/users/update.ts
pages/api/viewingPermissions/create.ts
pages/api/viewingPermissions/delete.ts
pages/api/viewingPermissions/read.ts

Added CRUD functionality for the users and viewing permission tables! Side note: Viewing Permissions do not have the update functionality as per our discussions on Thursday
Link to Postman workspace: https://app.getpostman.com/join-team?invite_code=cfbf914cf9a9d1ae51fb29227f98860b&ws=96e23380-723e-4345-a916-f2ccdfe54700
@sydbui just an update that Users CRUD functions work now :)
Did not add anything to the database. However wanted to bring up that the unique ID for the viewing permissions schema is currently not auto incremented and will probably need to be changed in the future. 
Create User
Read User
Update User
Delete User
Create Viewing Permission
Read Viewing Permission
Delete Viewing Permission
CC: @erinysong @shannonmhong

User and Viewing Permissions CRUD

---

pages/playerProfile.tsx
pages/playerprofile.tsx

(first draft, no props being passed in)
- Worked with @sydbui to create a first draft of the player profile page (above the section title)
- Followed dimensions on [Player Profile Figma](https://www.figma.com/file/OXSYtCJxra1NzMT7I58HVx/OGSC?node-id=58%3A9) as closely as possibly in accordance with [Tailwind's spacing options](https://tailwindcss.com/docs/customizing-spacing)
@shannonmhong you might be able to take some of this for Admin Dashboard Navbar!
Player profile with _Overview tab_ selected
CC: @erinysong

Player profile navbar outline

---

bin/seed-database.ts
migrations/20201025034105-UseSerialIdsForViewingPermissions.ts
pages/api/admin/viewingPermissions/create.ts
prisma/schema.prisma

Addresses future work specified in #19.
* Adds cleanup step to remove all @ogsc.dev users before seeding the database
* Adds admin-type user (admin@ogsc.dev)
* Adds mentor-type users (mentor[0-9]@ogsc.dev), connected to their corresponding player-type users (player[0-9]@ogsc.dev).
* Adds a migration to add an ID sequence for the viewing_permissions table. This is required for Prisma to recognize that the ID does not need to be supplied on creation.
CC: @erinysong

Seed script updates: admin user, mentors + viewing permissions

---

.vscode/settings.json
components/Button.tsx
components/DashboardLayout/Sidebar.tsx
components/FormField.tsx
components/Modal.tsx
interfaces/index.ts
migrations/20201028050959-AddPhoneNumberToUsers.ts
package.json
pages/admin/invite/index.tsx
pages/admin/invite/new.tsx
pages/api/admin/users/create.ts
pages/api/users/index.ts
prisma/schema.prisma
styles/globals.css
yarn.lock

* Adds /admin/new invite page form
* Creates new components for styling: FormField (to automatically set up a label and error messaging element around the input) and Modal
* Adds react-hook-form + @hookform/joi at the suggestion of @joyydong, for tracking stateful values and validations in the form
* Adds migration and schema update for storing phone numbers of users
**Future work:**
* Validate and standardize phone number inputs with libphonenumber or similar
* Roles should present role-specific questions, whose answers should influence part of the API request payload to POST /api/admin/invites
* 95f4031 introduces `20201028050959-AddPhoneNumberToUsers`, which adds an optional string-type `phone_number` column to the users table.
CC: @erinysong

Add admin "invite new user" page

---

bin/seed-database.ts
interfaces/user.ts
migrations/20201108050951-CreateAbsencesTable.ts
pages/api/users/me.ts
pages/player/[id].tsx
prisma/schema.prisma

* Create absences table linked to users
* Updates Prisma schema and DB seeding script to reflect absences updates
* The seed script will add 0-3 absences for every type (school, academic, athletic) for random reasons
* Run `yarn db:migrate up` and `yarn db:seed`. Verify that the migration and seed succeeds without error.
* `20201108050951-CreateAbsencesTable`: Creates absences table
CC: @erinysong

Create absences table with schema/seed updates

---

lib/notify/index.ts
lib/notify/sendgrid.ts
package.json
yarn.lock

* Adds new Notifier implementation that uses Sendgrid's email API
* Adds `@sendgrid/mail` as a dependency. You'll need to run yarn after pulling these changes.
* Add `SENDGRID_API_KEY` to your .env file (lib/notify will detect if this is present and opt to use the Sendgrid notifier over the development notifier if so) — I've added a staging API key [here (internal).](https://calblueprint.slack.com/archives/G01B26QJ10T/p1604819331041000)
* Visit http://localhost:3000/admin/invite as an admin and invite a user with your email. Submit the form.
* Verify that you receive a signup invitation email.
CC: @erinysong

Add Sendgrid notifier for staging/prod uses

---

package.json
yarn.lock

Reverts #48 and #49. We are affected by prisma/prisma#4216, which comments out `timestamptz` times from our schema. We will attempt an upgrade again once Prisma figures out the correct handling for these timestamp with timezone types.

Revert Prisma 2.11.0 bumps

---

bin/seed-database.ts
components/Player/PlayerFormLayout/ProgressBar.tsx
components/Player/Profile.tsx
components/Player/ValueHistoryView.tsx
components/PlayersDashboard.tsx
constants/colors.js
interfaces/user.ts
package.json
pages/admin/players/index.tsx
pages/admin/players/playerForm/academics.tsx
pages/admin/players/playerForm/attendence.tsx
pages/admin/players/playerForm/engagement.tsx
pages/admin/players/playerForm/highlights.tsx
pages/admin/players/playerForm/index.tsx
pages/admin/players/playerForm/overview.tsx
pages/admin/players/playerForm/physicalWellness.tsx
public/chevron.svg
styles/globals.css
tailwind.config.js
tsconfig.json
utils/buildUserProfile.ts
yarn.lock

* Update seeding script to insert values across a range of dates from 2020
* Move colors to constants file (now imported from Tailwind) for use in the rest of the codebase (with types!)
* Adds ValueHistoryView component, which displays an average of values over time, with toggleable graph/table views
* Adds `victory` as a new dependency for SVG charting
- (_Separate ticket_) Migrate engagement score values over to object structure that can include a description (and a date, to support retroactive scoring)
- Run `yarn` to pull in new dependencies.
- For best results, re-run `yarn db:seed`.
- Navigate to a player profile's Engagement tab.
CC: @erinysong

Engagement score graphs and tables

---

components/Card.tsx
components/Combobox.tsx
package.json
pages/admin/invite/new.tsx
pages/api/admin/users/create.ts
pages/api/admin/viewingPermissions/create.ts

- Combobox with cards that have removal abilities
- Updated endpoint to create corresponding new viewing permissions upon submitting form
- Go to http://localhost:3000/admin/invite/new
- Select mentor, parent, or donor as role in order to see the Linked Players options
- Search, add, and remove players
- Press submit
- Check the database for 1) a newly created mentor/parent/donor and 2) new viewing permissions for each player
- ~~due to the [non-null argument type for `selectItem`](https://github.com/calblueprint/ogsc/pull/54/commits/ee17c5d4cb889fb79c3fb964823b8e572e419c27#diff-68d1c6cb11ee54707043a5e5746e3fa051b0cfed4b9ebb2724940d91a796ceaaL71) function (part of Downshift Combobox)—not sure how to handle this, @sydbui also has this issue~~
- ~~maybe we …

Completed player association flow

---

bin/seed-database.ts
components/Player/ValueHistoryView.tsx
interfaces/user.ts
utils/buildUserProfile.ts

* Adds two new ProfileFieldValue types: IntegerWithComment, FloatWithComment
* IntegerWithComment is now being used for all engagement score values
* FloatWithComment is now being used for GPA values
* Updates seed to account for the new deserialized structure for these values:
* `{ comment: "Some comment", value: 3 }`
* Updates ValueHistoryView component to read from `.value` in the case of WithComment profile fields and display comments in the table
* Run `yarn db:seed` (required — there is no migration path for the old profile field values)
* Visit the player profile Engagement or GPA tabs
* Observe that comments appear in the rows of the table view
CC: @erinysong

Add IntegerWithComment, FloatWithComment types for GPA and engagement

---

pages/api/admin/users/readMany.ts
pages/api/admin/users/search/[phrase].ts
pages/api/admin/users/search/index.ts
pages/users/signUp/index.tsx

The following PR modifies the players dashboard and the players sub-component of the users dashboard to pull all of the players in accordance to Shannon's database changes that give each player user the user role of "Player".
Minor style fix has also been made in which the focus text of sign-up was changed to blue.
Go to /admin/users and navigate to the players tab. The dashboard should now include all player users.The same results should appear on the /admin/players tab.
The user should also now be able to successfully access all players when adding player associations to the combobox component when adding new player profile accesses to a user.
[X] …

Refactor Players Dashboard to Reflect Shannon's DB Changes

---

prisma/schema.prisma

Fixes createdAt/updatedAt/emailVerified column mapping that got inadvertently changed in 31b36d1.
* Run `yarn build` (and `yarn prisma generate` beforehand). Verify that the app builds successfully.
* See #74 for 31b36d1.
CC: @erinysong

Build hotfix: update createdAt/updatedAt/emailVerified column mapping

---

prisma/schema.prisma

My DB state was a bit different due to some work on the viewing permissions rename. I reset my DB state and found that this line may cause diffs on introspection from a correctly-built DB.
* Verify that `yarn build` passes.
* #78 — original hotfix
CC: @erinysong

Update to viewing_permissions non-null properties

---

components/Modal.tsx
components/Player/PlayerForm/AddAbsences.tsx
components/Player/PlayerForm/AddGPAField.tsx
components/Player/PlayerForm/AddScoreField.tsx
components/Player/PlayerForm/DisciplinaryField.tsx
components/Player/PlayerForm/newPlayer.tsx
pages/[role]/players/[id].tsx
pages/admin/invite/index.tsx
pages/admin/players/playerForm/academics.tsx
pages/admin/players/playerForm/attendence.tsx
pages/admin/players/playerForm/engagement.tsx

Turn form fields into modal & Fixed multiple invites sent bug
- fixed bug of a double user invite sent within form
- turned the form fields for attendance, engagement, gpa, and disciplinary actions into modals
- [] work when you run `yarn build`?
CC: @erinysong

Fixed multiple user invite sent bug & turn form into modal

---

.babelrc
components/Player/Profile.tsx
lib/access/definitions.ts
lib/access/resolve.ts
lib/access/types.ts
package.json
pages/[role]/players/[id].tsx
prisma/schema.prisma
utils/filterPlayerProfileRead.ts
utils/filterPlayerProfileWrite.ts
yarn.lock

* Creates lib/access structure for defining "profile access definitions," which refer to maps of profile field keys to true/false values (or functions that resolve to true/false values)
* Defines initial profile access definitions according to this spec: https://www.notion.so/User-Access-Wrapper-Functions-2b8763b81a3e4c4f815d065959bda929#d2bb6de79aa74337b1c83a3779595939
* Adds utils `filterPlayerProfileRead` and `filterPlayerProfileWrite` for wrapping around IPlayer/UserUpdateArgs across the app — these utils provide role-sensitive access control
* Updates player profile page to use `filterPlayerProfileRead` util
* Adds `superjson` and its Babel plugin for next as a dependency to the app — these libraries handle `getServerSideProps` serialization/deserialization that support types like …

Implement access control by user role

---

components/Combobox.tsx
pages/admin/invite/new.tsx
pages/api/admin/users/create.ts
pages/users/acceptInvite/acceptInvite2.tsx

- Generalizing combobox from the invites form for reusability in the user request pages
- Props now include `role` to generate the subtext (`selectedPlayers, setSelectedPlayers` still being passed in)
- Small create endpoint fix from the user role refactor
- visit http://localhost:3000/admin/invite/new (and soon user request pages)
@christopher-grey ready for use in user requests!
CC: @erinysong

More General Combobox Component

---

pages/admin/user/[id].tsx
pages/api/admin/users/delete.ts

- admins can delete users from a user's profile
- when deleting a user, also deleting all references in other tables to that user
(cascade on delete for many-to-many relationships don't work on prisma right now so just did it manually, an issue @ethanlee16 also mentioned in another PR)
issue prisma/prisma#2057
1) from the "users/admin" page, click on any user
2) from the users profile, try deleting a user
3) should take you to the users dashboard after clicking "delete"
[X] successfully run `yarn dev` and support all changes that your branch intends to perform?
CC: @erinysong

refactor deleting users and fix bugs in delete

---

database.json
package.json

* Attempt to fix `yarn db:migrate up` while preventing the SSL error in production/Heroku environments. This PR tests itself with a review app.
CC: @sydbui

Move ssl option to prod config, specify prod env in postbuild command

---

.vscode/settings.json
components/Combobox.tsx
pages/admin/user/[id].tsx
pages/api/admin/users/update.ts

- updated front end to allow adding and deleting linked players on the user profile page as well
- also included update to vscode settings to allow auto-prettier styling on save
- did not finish styling but will do so by next sprint task, just wanted to get the functionality out so that Joy and CJ could use it
go to a mentor's profile page and try editing their related players
[X] successfully run `yarn dev` and support all changes that your branch intends to perform?
@christopher-grey @joyydong finished the update user API to allow editing of related players! tagging so …

Update admin/user/update API Endpoint to allow for role updating 

---

pages/api/admin/users/create.ts
pages/api/admin/users/update.ts

Updated the `update` api to clear linked players if `role === players` (admin case had already been covered)
- go to http://localhost:3000/admin/invite and click one of the pending (non-admin or non-player) invites in the table 
- change the role to player or admin and save
- check db to verify that this user no longer has any linked player
CC: @sydbui

Some last fixes on the User Invites ("Your Pending Invites") table

---

utils/filterPlayerProfileWrite.ts

Hotfixes an issue where `filterPlayerProfileWrite` was not handling scenarios where the `user` argument was an Admin-type user.
* Validate that admin users can update player profiles.
* Validate that admin users can create player profiles.
Issue introduced by #142.
CC: @sydbui

Handle case where filterPlayerProfileWrite receives an admin user

---

pages/admin/invite/[id].tsx

- bug fix with "undefined role" in pending invites table
(used to have this error when we try to resend invite without linked players)
- go to http://localhost:3000/admin/invite 
- click on an invite in the pending invites table 
- resend an invite without any linked players and verify that it doesn't error
CC: @sydbui

Pending Invites Table bug

---

components/Modal.tsx
components/Player/AbsenceTable.tsx
components/Player/EditMore.tsx
components/Player/PlayerFormLayout/ProgressBar.tsx
components/Player/PlayerFormLayout/index.tsx
components/Player/Profile.tsx
components/Player/ProfileFieldEditor.tsx
components/Player/ProfileFieldEditorModal.tsx
components/Player/ValueHistoryGraph.tsx
components/Player/ValueHistoryTable.tsx
components/Player/ValueHistoryView.tsx
components/userRequest.tsx
lib/toast.ts
pages/[role]/[id].tsx
pages/[role]/players/[id].tsx
pages/_app.tsx
pages/admin/invite/[id].tsx
pages/admin/invite/index.tsx
pages/admin/invite/userAccountPage/[id].tsx
pages/admin/players/create/[profileCategory].tsx
styles/globals.css
utils/useCanEditField.ts

* Resolves #221: prevents moving forward in the create form if the player has not been supplied.
* Makes buttons for creating engagement scores/absences sensitive to lib/access definitions
* Adds back toast notifications to creates/updates made in ValueHistoryTable and AbsenceTable, standardizes toast settings in lib/toast
* Refactors Modal to use @headlessui/dialog, with stylistic updates and accessibility improvements
* Resolves #217.
* Validate that the repro case in #221 is resolved; navigation to future steps should be prevented in UI if player is not selected.
* Validate that for non-admin users, engagement score/absence creation is not available or displayed in their respective table views
* Validate that toast notifications are appearing for creates/updates of engagement scores …

Create form follow-on updates

---

components/userRequest.tsx
lib/notify/sendgrid.ts
lib/notify/types.ts
pages/admin/invite/[id].tsx
pages/admin/invite/userAccountPage/[id].tsx
pages/api/admin/users/update.ts

- SendGrid for userInvites (when an admin Accepts their account it sends an email that lets the user know that their account has been accepted and they can now log in) 
accept an entry under Invitation Requests on http://localhost:3000/admin/invite and check that an email has been sent
CC: @sydbui

Sendgrid on accepted user account

---

components/Player/Profile.tsx
components/Player/ProfileFieldCell.tsx

* Prevent returning null if the viewer of a profile has edit access, from ProfileFieldCell
* Allow a category to appear if any field within it should be editable by the viewer
- Create a sparse player profile from the player creation form, meaning that some fields (e.g., Academic Engagement Score) do not appear.
- Validate that the resulting player profile continues to show all tabs and fields from an admin's perspective, and allow the entry of data while viewing an already-created profile.
CC: @sydbui

Allow empty fields to show up if the viewer has edit access

---

components/Player/ProfileFieldCell.tsx

* Make URLs clickable in view mode
* Detect YouTube URLs and automatically embed if available
* Validate that Highlights and Intro Video fields are appearing as clickable links on the profile.
* Try adding a YouTube URL, i.e. "https://www.youtube.com/watch?v=kR77WlHRZrs" to one of the URL fields.
* Validate that YouTube embeds are appearing inline with the profile.
YouTube embed:
Link click:
CC: @sydbui

Make URL types clickable and allow for YouTube video embeds

---

.github/workflows/forks.yml
pages/api/admin/users/addImage.ts
pages/api/profilePicture/index.ts

* Sets S3 config options with `signatureVersion` set as "v4" in both places (production bucket requires v4 signatures)
* Update fork sync job option to only listen on pushes to main
* Regression test image uploads and validate that image viewing/uploading still works as expected.
CC: @sydbui

Set signatureVersion for S3, restrict fork sync to pushes on main
