calblueprint/ogsc

migrations/20201004192007-playersProfile.ts
prisma/schema.prisma
yarn.lock

- added migration to initialize players table 
- playersProfiles : add players table 
CC: @erinysong

Players Table Migration

---

pages/api/players/create.ts
pages/api/players/delete.ts
pages/api/players/read.ts
pages/api/players/update.ts
prisma/schema.prisma

CRUD endpoints for Player
- added CRUD endpoints for Player
- fixed typo in primsa.schema 
- need User endpoints to be able to test 
CC: @erinysong

CRUD endpoints for Player

---

.eslintrc.js
bin/seed-database.ts
package.json
yarn.lock

* Adds a script, `yarn db:seed`, to seed 10 new users with fake emails/names/passwords
* Adds dependencies: orm (for CLI loading states) and faker (for easy-to-generate random names/emails/passwords)
**Future work:**
* Add profiles (this will not apply to all users) — seed multiple kinds of users during the script
* Add viewing permissions — seed relationships between the created users 
CC: @erinysong

Database seed scripts

---

pages/_app.tsx
pages/users/signUp/index.tsx
pages/users/signUp/signUp2.tsx
utils/updateAction.ts

- Fixing `little-state-machine` getStore issue
- Moved static file `updateAction.ts` from pages to utils
CC: @erinysong

Fixing store issue + static file issue

---

pages/api/admin/users/search/[phrase].ts
pages/api/admin/users/search/index.ts

Made Requested Changes to ReadAllPlayers Endpoint
- took out titleText and changed to "mode: 'insensitive' "
- used exported USER_PAGE_SIZE
[] successfully run `yarn:db-migrate up` without yielding any errors?
[] successfully run `yarn prisma introspect` without yielding any errors?
[] successfully run `yarn dev` and support all changes that your branch intends to perform?
CC: @erinysong

Made Requested Changes ReadAllPlayers Endpoint

---

components/DashboardLayout/Sidebar.tsx
components/PlayersDashboard.tsx
pages/admin/players.tsx

Players Dashboard with Search Bar
- implemented Players Dashboard by referencing Shannon's Users Dashboard
- implement search bar for Players Dashboard 
- first: seed data base
- second: run yarn dev
- third: go to http://localhost:3000/admin/players
- @joyydong  might help with your sprint task
CC: @erinysong

Players Dashboard with Search Bar

---

components/Icon.tsx
components/PageNav.tsx
components/UserDashboard.tsx
constants/index.tsx
pages/admin/users.tsx
pages/api/admin/users/readMany.ts

- Can switch pages by clicking next and back
- Implemented caching so that it knows what pages have already been retrieved and only makes an API request every `USER_PAGE_SIZE` / `UI_PAGE_SIZE` pages (which is 21 / 7 = 3 right now)
- added constants file for easy sharing amongst components
NOTE: followed Rachel's styling for the most part, except hard-coded the spacing between components. need to eventually figure out how to make that flexible
(1) run `yarn dev`
(2) navigate to [localhost #]/admin/users
(3) click on previous and next to switch pages
[X] successfully run `yarn …

Complete Basic Page Navigation

---

Procfile
app.json
bin/seed-database.ts
bin/set-nextauth-url.ts
package.json
tsconfig.scripts.json
yarn.lock

* Creates a script, `bin/setNextAuthUrl`, to try to automatically set the `$NEXTAUTH_URL` config var when a review app gets created
* Adds app.json with an addon for review apps to provision a hobby-dev DB with each new review app
* This PR tests itself. If the review app launches with the correct env vars, it works!
CC: @erinysong

Create setNextAuthUrl postdeploy script with app.json

---

components/DashboardLayout/Sidebar.tsx

Scheduling and Notes are not anticipated to be a part of our MVP for this semester so our side navbars for now will not include them. Once we build out these features, we should add them back to the navbar so that we can access their routes.
[X] successfully run `yarn dev` and support all changes that your branch intends to perform?
CC: @erinysong

commented out calendar and notes from side navbar

---

components/Card.tsx
components/Combobox.tsx

- Card component that @sydbui needs for player profile form and I need for player associations 
- Fixed hover/highlight bug in the combobox
To use the card, import from components and use `<Card />` with the necessary props
CC: @erinysong

Card component + fixed highlight issue

---

bin/seed-database.ts
components/UserDashboard.tsx
pages/admin/user/[id].tsx
pages/admin/users.tsx
pages/api/admin/users/readMany.ts
pages/api/admin/users/update.ts
yarn.lock

- User roles now displayed on both user profile and user dashboard
- added search bar to user dashboard
- filtering by role on user dashboard
- user profile correctly re-renders on save after editing
- radio button default selected on correct user role
1) re-run `yarn db:seed` (may need to delete current users)
2) run ` yarn dev`
3) go to `...localhostnumber/admin/users and click around
[X] successfully run `yarn dev` and support all changes that your branch intends to perform?
N/A
not a migration but edited the seed script to include users with all role types and have the …

Add in user roles to dashboard and user profile

---

components/Player/PlayerForm/newPlayer.tsx
migrations/20201128005528-AddAcceptedAtToUserInvite.ts
pages/_app.tsx
pages/admin/players/playerForm/highlights.tsx
pages/api/admin/users/update.ts
pages/api/users/index.ts
pages/users/acceptInvite/acceptInvite2.tsx
pages/users/acceptInvite/error.tsx
pages/users/acceptInvite/index.tsx
pages/users/signUp/index.tsx
pages/users/signUp/signUp2.tsx
prisma/schema.prisma
utils/updateActionAcceptInvite.ts
utils/updateActionSignUp.ts

Reverted [Joy's User Accept Invite Flow PR](https://github.com/calblueprint/ogsc/pull/75) to accommodate changes made from RFC refactoring in main. The changes should be the exact same as the ones in the PR linked prior.
Refer to [https://github.com/calblueprint/ogsc/pull/75](https://github.com/calblueprint/ogsc/pull/75).
[x] work when you run `yarn build`?
[x] successfully run `yarn:db-migrate up` without yielding any errors?
[x] successfully run `yarn prisma introspect` without yielding any errors?
[x] successfully run `yarn dev` and support all changes that your branch intends to perform?
_Optional - if you …

refactored joy's branch to integrate rfc changes

---

components/Player/AbsenceFieldContent.tsx
components/Player/AbsenceTable.tsx
components/Player/AddAbsence.tsx
components/Player/AddGPA.tsx
components/Player/AddScore.tsx
components/Player/DeleteField.tsx
components/Player/EditAbsence.tsx
components/Player/EditMore.tsx
components/Player/EditMoreAbsence.tsx
components/Player/EditScore.tsx
components/Player/GPAFieldContent.tsx
components/Player/PlayerForm/CreateAbsences.tsx
components/Player/PlayerForm/CreateGPAField.tsx
components/Player/PlayerForm/CreateScoreField.tsx
components/Player/PlayerForm/DateComboBox.tsx
components/Player/Profile.tsx
components/Player/ScoreFieldContent.tsx
components/Player/ValueHistoryView.tsx
pages/admin/players/playerForm/academics.tsx
pages/admin/players/playerForm/attendence.tsx
pages/admin/players/playerForm/engagement.tsx
pages/api/admin/users/player/delete.ts
pages/api/admin/users/player/deleteAbsences.ts

Implement Add and Delete Profile Fields
- you can now add and delete profile Fields 
- two new endpoints created for delete 
- yarn dev -> go to a /local/admin/players -> click on a player and try it out
CC: @erinysong

Implement Add and Delete Profile Fields

---

pages/admin/invite/new.tsx
pages/api/admin/users/create.ts
pages/api/users/index.ts
pages/users/acceptInvite/index.tsx
pages/users/signUp/index.tsx
pages/users/signUp/signUp2.tsx

- Fixing Joi Validation errors (where optional fields were being required)
- http://localhost:3000/admin/invite/new: linkedPlayers is no longer required (so it won't block you from submitting the form when the user is a player)
- http://localhost:3000/users/signUp/signUp2: phone number, role, admin are no longer required
CC: @erinysong

WIP joi validation fixes

---

pages/admin/players/playerForm/highlights.tsx

_Describe your feature here_
[] successfully run `yarn:db-migrate up` without yielding any errors?
[] successfully run `yarn prisma introspect` without yielding any errors?
[] successfully run `yarn dev` and support all changes that your branch intends to perform?
CC: @erinysong

Update Func Name

---

components/UserDashboard.tsx
components/userRequest.tsx
pages/admin/invite/index.tsx

Updated user table and a few other small styling bugs
N/A
navigate to ./admin/users page
[x] work when you run `yarn build`?
[x] successfully run `yarn:db-migrate up` without yielding any errors?
[x] successfully run `yarn prisma introspect` without yielding any errors?
[x] successfully run `yarn dev` and support all changes that your branch intends to perform?
N/A
N/A
CC: @sydbui

Styling Bugs Fixes

---

components/DashboardLayout/Sidebar.tsx

Logout Functionality to PopOut 
- allows user to logout and then is redirected to sign-in page 
@shannonmhong  you will still need to add a logout button to the user profile page!
CC: @sydbui

Logout Functionality to PopOut 

---

components/DashboardLayout/Sidebar.tsx
pages/admin/users.tsx
pages/api/auth/[...nextauth].ts
pages/api/players/search.ts
pages/auth/signin.tsx
pages/users/signUp/index.tsx

fix bugs described in https://www.notion.so/calblueprint/Error-handling-Notes-ca7fbffec1084097a414fcdd16c8e9d1
- email error styling on sign up page
- only show active players on player dashboard
- remove user dashboard link from non-admin sidebar
- fix highlight arrow bug on sidebar for players
- add error to sign in page to prevent users with PendingAdminApproval status from signing in (i restyled the error message but i'm not sure where it should be located so i just guessed. lmk if you think there's a better place it can be!)
NOTE: didn't add in the logo on the sidebar bc haven't gotten a pic from rach yet
still need to work on the rest of the sprint once everyone's code is merged in!
Error for users who try to sign in who have not been approved by admins yet
Does your branch (check …

Fix some bugs

---

bin/seed-database.ts
components/Player/NotesTable.tsx
components/Player/Profile.tsx
interfaces/user.ts
migrations/20210423043915-ChangeNotesTableAuthorRelation.ts
migrations/20210423043915-ChangeNotesTableName.ts
migrations/20210423081440-AddNotesAuthorPlayerRelation.ts
pages/[role]/players/[id].tsx
prisma/schema.prisma

Added a couple new migrations to fix notes table
Added 2 migrations: 
-  20210423043915-ChangeNotesTableName.ts
-  20210423081440-AddNotesAuthorPlayerRelation.ts
CC: @sydbui

Added author and player recipient for Notes Table

---

migrations/20210423081440-AddNotesAuthorPlayerRelation.ts

Applies these changes to 20210423081440-AddNotesAuthorPlayerRelation.ts:
- Updates order of operations in down migration
- Removes foreign key before creating new one
- ⚠️ Clears the state of your notes table before proceeding (suppressing error about null values in new column)
- Switches to promisified migrate functions
* Validate that `yarn db:migrate up`, `yarn db:migrate down`, and up again runs without errors.
* Added in #238
CC: @sydbui

Hotfix migrations/ for possible states of local environments

---

components/PlayersDashboard.tsx
components/UserDashboard.tsx
components/pendingInvitesTable.tsx
components/userRequest.tsx
pages/admin/invite/userAccountPage/[id].tsx

Cleaned Up Styling for Dashboards
cleaned up styling for player, user, and invites dashboard 
[] successfully run `yarn:db-migrate up` without yielding any errors?
[] successfully run `yarn prisma introspect` without yielding any errors?
[] successfully run `yarn dev` and support all changes that your branch intends to perform?
CC: @sydbui

Cleaned Up Styling for Dashboards

---

pages/users/acceptInvite/acceptInvite2.tsx
pages/users/acceptInvite/confirmation.tsx

Add AcceptInvite Confirmation page
- adds a confirmation page for accept invite
[] successfully run `yarn:db-migrate up` without yielding any errors?
[] successfully run `yarn prisma introspect` without yielding any errors?
[] successfully run `yarn dev` and support all changes that your branch intends to perform?
CC: @sydbui

Add AcceptInvite Confirmation page

---

components/Card.tsx
components/Combobox.tsx
components/Icon.tsx
components/Player/PlayerFormLayout/index.tsx
pages/admin/players/create/index.tsx

* Miscellaneous styling improvements for player selection - fixed selection color from the previous color name, so keyboard navigation and selection is now more apparent
* Test all usages of Combobox component: player create form, user account invite page, invite edit page
Empty state:
CC: @sydbui

Styling improvements to player selection

---

components/Player/ProfileFieldCell.tsx

* Verify that links are only clickable from the text/icon combo
* Verify that the opacity is lowered on hover
https://share.getcloudapp.com/rRuGBPwN
CC: @sydbui

Fix display issue: link clickable area bound to content, add hover opacity change

---

components/Player/NotesTable.tsx

fixed a paragraph styling and y scroll issue
- [] successfully run `yarn dev` and support all changes that your branch intends to perform?
CC: @sydbui

small notes styling fix

---

.github/workflows/forks.yml
lib/notify/sendgrid.ts

* Add email templates for production deployment
* Set fork sync destination to OaklandGenesis/ogsc
* Regression test email notifications on staging environments. Verify that notifications continue to function as expected.
CC: @sydbui

Add email production templates map, update fork sync

---

lib/access/definitions.ts
pages/[role]/players/[id].tsx
pages/admin/invite/[id].tsx
pages/admin/invite/index.tsx
prisma/schema.prisma

- fill in dead text
- included ACT, SAT, Internal Assesement, and standardized testing for Player access 
- remove academic plans from standardReadAccess 
- [] successfully run `yarn dev` and support all changes that your branch intends to perform?
CC: @sydbui

Fill in Dead Text and changed lib/access for academic 

---

components/PlayersDashboard.tsx
pages/[role]/players/[id].tsx
utils/useProfilePicture.ts

fetching profile pictures of players and displaying them on the players dashboard
Verify that any updated profile pictures show up when visiting http://localhost:3000/admin/players
CC: @sydbui

Image fetching

---

components/DashboardLayout/Sidebar.tsx
components/PlayersDashboard.tsx
components/UserDashboard.tsx
constants/index.tsx
pages/[role]/[id].tsx
pages/[role]/players/[id].tsx
pages/api/players/images/[id].ts
utils/useProfilePicture.ts

- trying to do image fetching on the members table (not the players table)
- following the steps outlined here https://www.notion.so/calblueprint/Joy-25ccdc553fa64b8f978c8504e34d3385#bbbe8f4d75e946a8b424a89a6d2b4e9a 
im currently testing with the players id page: http://localhost:3000/admin/players/[id]
- it should fetch the correct image for a player that has a profile picture uploaded, but currently just gets the placeholder bc the 404
CC: @sydbui

Members dashboard image uploads
